/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedRouteImport } from './routes/protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as CollabSessionIdRouteImport } from './routes/collab.$sessionId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as AdminQuestionsIndexRouteImport } from './routes/admin/questions/index'
import { Route as AdminQuestionsAddRouteImport } from './routes/admin/questions/add'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabSessionIdRoute = CollabSessionIdRouteImport.update({
  id: '/collab/$sessionId',
  path: '/collab/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsIndexRoute = AdminQuestionsIndexRouteImport.update({
  id: '/admin/questions/',
  path: '/admin/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsAddRoute = AdminQuestionsAddRouteImport.update({
  id: '/admin/questions/add',
  path: '/admin/questions/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/questions/add': typeof AdminQuestionsAddRoute
  '/admin/questions': typeof AdminQuestionsIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/questions/add': typeof AdminQuestionsAddRoute
  '/admin/questions': typeof AdminQuestionsIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/questions/add': typeof AdminQuestionsAddRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/protected'
    | '/signup'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/profile'
    | '/admin/questions/add'
    | '/admin/questions'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/protected'
    | '/signup'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/profile'
    | '/admin/questions/add'
    | '/admin/questions'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/protected'
    | '/signup'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/profile/'
    | '/admin/questions/add'
    | '/admin/questions/'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProtectedRoute: typeof ProtectedRoute
  SignupRoute: typeof SignupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CollabSessionIdRoute: typeof CollabSessionIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AdminQuestionsAddRoute: typeof AdminQuestionsAddRoute
  AdminQuestionsIndexRoute: typeof AdminQuestionsIndexRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/$sessionId': {
      id: '/collab/$sessionId'
      path: '/collab/$sessionId'
      fullPath: '/collab/$sessionId'
      preLoaderRoute: typeof CollabSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions/': {
      id: '/admin/questions/'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions/add': {
      id: '/admin/questions/add'
      path: '/admin/questions/add'
      fullPath: '/admin/questions/add'
      preLoaderRoute: typeof AdminQuestionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProtectedRoute: ProtectedRoute,
  SignupRoute: SignupRoute,
  AdminUsersRoute: AdminUsersRoute,
  CollabSessionIdRoute: CollabSessionIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AdminQuestionsAddRoute: AdminQuestionsAddRoute,
  AdminQuestionsIndexRoute: AdminQuestionsIndexRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
