/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedRouteImport } from './routes/protected'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as CollabSessionIdRouteImport } from './routes/collab.$sessionId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as UserUsernameIndexRouteImport } from './routes/user/$username/index'
import { Route as UserUsernameEditRouteImport } from './routes/user/$username/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabSessionIdRoute = CollabSessionIdRouteImport.update({
  id: '/collab/$sessionId',
  path: '/collab/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameIndexRoute = UserUsernameIndexRouteImport.update({
  id: '/user/$username/',
  path: '/user/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameEditRoute = UserUsernameEditRouteImport.update({
  id: '/user/$username/edit',
  path: '/user/$username/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/user': typeof UserIndexRoute
  '/user/$username/edit': typeof UserUsernameEditRoute
  '/user/$username': typeof UserUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/user': typeof UserIndexRoute
  '/user/$username/edit': typeof UserUsernameEditRoute
  '/user/$username': typeof UserUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/protected': typeof ProtectedRoute
  '/signup': typeof SignupRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collab/$sessionId': typeof CollabSessionIdRoute
  '/user/': typeof UserIndexRoute
  '/user/$username/edit': typeof UserUsernameEditRoute
  '/user/$username/': typeof UserUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/protected'
    | '/signup'
    | '/admin/questions'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/user'
    | '/user/$username/edit'
    | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/protected'
    | '/signup'
    | '/admin/questions'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/user'
    | '/user/$username/edit'
    | '/user/$username'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/profile'
    | '/protected'
    | '/signup'
    | '/admin/questions'
    | '/admin/users'
    | '/collab/$sessionId'
    | '/user/'
    | '/user/$username/edit'
    | '/user/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProtectedRoute: typeof ProtectedRoute
  SignupRoute: typeof SignupRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CollabSessionIdRoute: typeof CollabSessionIdRoute
  UserIndexRoute: typeof UserIndexRoute
  UserUsernameEditRoute: typeof UserUsernameEditRoute
  UserUsernameIndexRoute: typeof UserUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/$sessionId': {
      id: '/collab/$sessionId'
      path: '/collab/$sessionId'
      fullPath: '/collab/$sessionId'
      preLoaderRoute: typeof CollabSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/': {
      id: '/user/$username/'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/edit': {
      id: '/user/$username/edit'
      path: '/user/$username/edit'
      fullPath: '/user/$username/edit'
      preLoaderRoute: typeof UserUsernameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProtectedRoute: ProtectedRoute,
  SignupRoute: SignupRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CollabSessionIdRoute: CollabSessionIdRoute,
  UserIndexRoute: UserIndexRoute,
  UserUsernameEditRoute: UserUsernameEditRoute,
  UserUsernameIndexRoute: UserUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
